version: "3"

services:
  dev-server:
    container_name: dev-server
    build:
      context: ./
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - 8080:80
    volumes:
      - ./src:/var/www/html
    depends_on:
      - dev-db
    networks:
      - dev-network


  dev-db:
    container_name: dev-db
    image: mysql:latest
    restart: always
    env_file:
      - ./.env
    ports:
      - 3306:3306
    volumes:
      - ./db/mysql-data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    command: --default-authentication-plugin=mysql_native_password --innodb-use-native-aio=0 --skip-name-resolve
    networks:
      - dev-network

networks:
  dev-network:
    driver: bridge